In [1]:
from dmipy.signal_models import cylinder_models
from dmipy.signal_models import capped_cylinder_models
from dmipy.core import modeling_framework
from dmipy.data import saved_acquisition_schemes
import numpy as np
from os.path import join
from dmipy.core import modeling_framework
from dmipy.core.acquisition_scheme import acquisition_scheme_from_bvalues
from dmipy.core.acquisition_scheme import acquisition_scheme_from_gradient_strengths
from os.path import join
import numpy as np
from dmipy.core.modeling_framework import MultiCompartmentModel

In [2]:
# we can then load the parameters themselves and convert them to SI units:
acquisition_path = modeling_framework.GRADIENT_TABLES_PATH
#bvalues = np.loadtxt(join(acquisition_path, 'bvals_hcp_wu_minn.txt'))  # given in s/mm^2
bvalues = np.array([25,50,100,250,500,750,1000,1500,2000])
bvalues_SI = bvalues * 1e6  # now given in SI units as s/m^2
#gradient_directions4= np.loadtxt(join(acquisition_path, 'bvecs_hcp_wu_minn.txt'))  # on the unit sphere
gradient_directions = []
for i in range(len(bvalues)):
    gradient_directions.append(np.array([0.57735027, 0.57735027, 0.57735027]))
    
gradient_directions = np.array(gradient_directions)
# The delta and Delta times we know from the HCP documentation in seconds
delta = 0.010  
Delta = 0.014 

# The acquisition scheme we use in the toolbox is then created as follows:
acq_scheme = acquisition_scheme_from_bvalues(bvalues_SI, gradient_directions, delta, Delta)
acq_scheme.print_acquisition_info

Acquisition scheme summary

total number of measurements: 9
number of b0 measurements: 0
number of DWI shells: 7

shell_index |# of DWIs |bvalue [s/mm^2] |gradient strength [mT/m] |delta [ms] |Delta[ms] |TE[ms]
0           |3         |58              |18                       |10.0       |14.0      |N/A  
1           |1         |250             |57                       |10.0       |14.0      |N/A  
2           |1         |500             |80                       |10.0       |14.0      |N/A  
3           |1         |750             |99                       |10.0       |14.0      |N/A  
4           |1         |1000            |114                      |10.0       |14.0      |N/A  
5           |1         |1500            |140                      |10.0       |14.0      |N/A  
6           |1         |2000            |161                      |10.0       |14.0      |N/A  


C:\Users\Mx\anaconda3\lib\site-packages\dmipy\core\acquisition_scheme.py:179: UserWarning: No b0 measurements were detected. Check if the b0_threshold option is high enough, or if there is a mistake in the acquisition design.
  warn(msg)


In [3]:

stick = cylinder_models.C4CylinderGaussianPhaseApproximation(diffusion_perpendicular=1.7e-09)
lambda_par = 1.7e-09
diameter = 0.000004
mu = (0,0)
stick_model = MultiCompartmentModel(models=[stick])
parameter_vector = stick_model.parameters_to_parameter_vector(
    C4CylinderGaussianPhaseApproximation_1_lambda_par=lambda_par, C4CylinderGaussianPhaseApproximation_1_mu=mu, C4CylinderGaussianPhaseApproximation_1_diameter=diameter)
E = stick_model.simulate_signal(acq_scheme, parameter_vector)
E

We highly recommend installing pathos to take advantage of multicore processing.


array([0.98573647, 0.97167638, 0.94415499, 0.86618016, 0.75026806,
       0.64986731, 0.56290216, 0.42232752, 0.31685885])

In [4]:
# we can then load the parameters themselves and convert them to SI units:
acquisition_path = modeling_framework.GRADIENT_TABLES_PATH
#bvalues = np.loadtxt(join(acquisition_path, 'bvals_hcp_wu_minn.txt'))  # given in s/mm^2
bvalues = np.array([1000])
bvalues_SI = bvalues * 1e6  # now given in SI units as s/m^2
#gradient_directions4= np.loadtxt(join(acquisition_path, 'bvecs_hcp_wu_minn.txt'))  # on the unit sphere
gradient_directions = []
for i in range(len(bvalues)):
    gradient_directions.append(np.array([0.57735027, 0.57735027, 0.57735027]))
    
gradient_directions = np.array(gradient_directions)
# The delta and Delta times we know from the HCP documentation in seconds
delta = 0.010  
Delta = 0.014 
ES = []
# The acquisition scheme we use in the toolbox is then created as follows:
acq_scheme = acquisition_scheme_from_bvalues(bvalues_SI, gradient_directions, delta, Delta)
acq_scheme.print_acquisition_info
Ds = [1e-09,1.5e-09,2e-09,2.5e-09,3e-09,3.5e-09]
for i in range(len(Ds)):
    stick = cylinder_models.C4CylinderGaussianPhaseApproximation(diffusion_perpendicular=Ds[i])
    lambda_par = Ds[i]
    diameter = 0.000004
    mu = (0,0)
    stick_model = MultiCompartmentModel(models=[stick])
    parameter_vector = stick_model.parameters_to_parameter_vector(
        C4CylinderGaussianPhaseApproximation_1_lambda_par=lambda_par, C4CylinderGaussianPhaseApproximation_1_mu=mu, C4CylinderGaussianPhaseApproximation_1_diameter=diameter)
    E = stick_model.simulate_signal(acq_scheme, parameter_vector)
    ES.append(float(E))
    print(E)
ES

Acquisition scheme summary

total number of measurements: 1
number of b0 measurements: 0
number of DWI shells: 1

shell_index |# of DWIs |bvalue [s/mm^2] |gradient strength [mT/m] |delta [ms] |Delta[ms] |TE[ms]
0           |1         |1000            |114                      |10.0       |14.0      |N/A  
We highly recommend installing pathos to take advantage of multicore processing.
0.7073926990825502
We highly recommend installing pathos to take advantage of multicore processing.
0.601122839505985
We highly recommend installing pathos to take advantage of multicore processing.
0.5099062449280763
We highly recommend installing pathos to take advantage of multicore processing.
0.43218927922672157
We highly recommend installing pathos to take advantage of multicore processing.
0.3661653989169666
We highly recommend installing pathos to take advantage of multicore processing.
0.31015192217890225


C:\Users\Mx\anaconda3\lib\site-packages\dmipy\core\acquisition_scheme.py:179: UserWarning: No b0 measurements were detected. Check if the b0_threshold option is high enough, or if there is a mistake in the acquisition design.
  warn(msg)


[0.7073926990825502,
 0.601122839505985,
 0.5099062449280763,
 0.43218927922672157,
 0.3661653989169666,
 0.31015192217890225]

In [5]:
# we can then load the parameters themselves and convert them to SI units:
acquisition_path = modeling_framework.GRADIENT_TABLES_PATH
#bvalues = np.loadtxt(join(acquisition_path, 'bvals_hcp_wu_minn.txt'))  # given in s/mm^2
bvalues = np.array([1000])
bvalues_SI = bvalues * 1e6  # now given in SI units as s/m^2
#gradient_directions4= np.loadtxt(join(acquisition_path, 'bvecs_hcp_wu_minn.txt'))  # on the unit sphere
gradient_directions = []
for i in range(len(bvalues)):
    gradient_directions.append(np.array([0.57735027, 0.57735027, 0.57735027]))
    
gradient_directions = np.array(gradient_directions)
# The delta and Delta times we know from the HCP documentation in seconds
delta = 0.010  
Delta = 0.014 
ES = []
# The acquisition scheme we use in the toolbox is then created as follows:
acq_scheme = acquisition_scheme_from_bvalues(bvalues_SI, gradient_directions, delta, Delta)
acq_scheme.print_acquisition_info
radii = [0.000001,0.0000015,0.000002,0.0000025,0.000003,0.0000035,0.000004,0.0000045,0.000005,0.00001,0.00002,0.00005,0.0001]
for i in radii:
    stick = cylinder_models.C4CylinderGaussianPhaseApproximation(diffusion_perpendicular=1.7e-09)
    lambda_par = 1.7e-09
    diameter = i
    print(i*1000)
    mu = (0,0)
    stick_model = MultiCompartmentModel(models=[stick])
    parameter_vector = stick_model.parameters_to_parameter_vector(
        C4CylinderGaussianPhaseApproximation_1_lambda_par=lambda_par, C4CylinderGaussianPhaseApproximation_1_mu=mu, C4CylinderGaussianPhaseApproximation_1_diameter=diameter)
    E = stick_model.simulate_signal(acq_scheme, parameter_vector)
    ES.append(float(E))
    print(E)
ES

Acquisition scheme summary

total number of measurements: 1
number of b0 measurements: 0
number of DWI shells: 1

shell_index |# of DWIs |bvalue [s/mm^2] |gradient strength [mT/m] |delta [ms] |Delta[ms] |TE[ms]
0           |1         |1000            |114                      |10.0       |14.0      |N/A  
0.001
We highly recommend installing pathos to take advantage of multicore processing.
0.5673947368494777
0.0015
We highly recommend installing pathos to take advantage of multicore processing.
0.5673183572369455
0.002
We highly recommend installing pathos to take advantage of multicore processing.
0.5671147994004153
0.0025
We highly recommend installing pathos to take advantage of multicore processing.
0.5666915171700547
0.003
We highly recommend installing pathos to take advantage of multicore processing.
0.5659355436522632
0.0035
We highly recommend installing pathos to take advantage of multicore processing.
0.5647183281234853
0.004
We highly recommend installing pathos to take ad

[0.5673947368494777,
 0.5673183572369455,
 0.5671147994004153,
 0.5666915171700547,
 0.5659355436522632,
 0.5647183281234853,
 0.5629021637081453,
 0.560348902751626,
 0.5569313623627301,
 0.47347823746742546,
 0.3169053269633585,
 0.22507127602854954,
 0.20212039908154814]

In [6]:
0.02 / 1000

2e-05

In [7]:
deltas = np.array([0.01,0.02,0.05,0.1,0.2,0.5,1,2,3]) + 0.004
grads = []
strr = []
dirr = []
for i in range(len(deltas)):
    grads.append(0.004)
    strr.append(0.1)
    dirr.append(np.array([0.57735027, 0.57735027, 0.57735027]))
    
grads = np.array(grads)
strr = np.array(strr)
dirr = np.array(dirr)
    
acq_scheme = acquisition_scheme_from_gradient_strengths(strr,dirr, grads, deltas)
acq_scheme.print_acquisition_info


stick = cylinder_models.C4CylinderGaussianPhaseApproximation(diffusion_perpendicular=0.5e-09)
lambda_par = 0#1.7e-09
diameter = 0.00002
mu = (0,0)
stick_model = MultiCompartmentModel(models=[stick])
parameter_vector = stick_model.parameters_to_parameter_vector(
    C4CylinderGaussianPhaseApproximation_1_lambda_par=lambda_par, C4CylinderGaussianPhaseApproximation_1_mu=mu, C4CylinderGaussianPhaseApproximation_1_diameter=diameter)
E = stick_model.simulate_signal(acq_scheme, parameter_vector)
E

Acquisition scheme summary

total number of measurements: 9
number of b0 measurements: 0
number of DWI shells: 9

shell_index |# of DWIs |bvalue [s/mm^2] |gradient strength [mT/m] |delta [ms] |Delta[ms] |TE[ms]
0           |1         |145             |100                      |4.0        |14.0      |N/A  
1           |1         |259             |100                      |4.0        |24.0      |N/A  
2           |1         |603             |100                      |4.0        |54.00000000000001|N/A  
3           |1         |1175            |100                      |4.0        |104.00000000000001|N/A  
4           |1         |2320            |100                      |4.0        |204.00000000000003|N/A  
5           |1         |5755            |100                      |4.0        |504.0     |N/A  
6           |1         |11480           |100                      |4.0        |1004.0    |N/A  
7           |1         |22930           |100                      |4.0        |2004.0    |N/A 

array([0.96351661, 0.94123886, 0.89525193, 0.85745374, 0.83510995,
       0.83019621, 0.83016571, 0.8301657 , 0.8301657 ])

In [10]:
bs = np.array([145.2146014126501,
259.73715773177474,
603.3048266891487,
1175.917608284772,
2321.143171476019,
5756.819861049759,
11482.947677005992,
22935.203308918455,
34387.458940830926])

bvalues_SI = bs * 1e6 
deltas = []
grads = []
strr = []
dirr = []
for i in range(len(bs)):
    deltas.append(0.01)
    grads.append(0.01)
    dirr.append(np.array([0.57735027, 0.57735027, 0.57735027]))
    
delta = np.array(grads)
gradient_directions = np.array(dirr)
Delta = np.array(deltas)
    
acq_scheme = acquisition_scheme_from_bvalues(bvalues_SI, gradient_directions, delta, Delta)
acq_scheme.print_acquisition_info


stick = cylinder_models.C4CylinderGaussianPhaseApproximation(diffusion_perpendicular=0.5e-09)
lambda_par = 0#1.7e-09
diameter = 0.00002
mu = (0,0)
stick_model = MultiCompartmentModel(models=[stick])
parameter_vector = stick_model.parameters_to_parameter_vector(
    C4CylinderGaussianPhaseApproximation_1_lambda_par=lambda_par, C4CylinderGaussianPhaseApproximation_1_mu=mu, C4CylinderGaussianPhaseApproximation_1_diameter=diameter)
E = stick_model.simulate_signal(acq_scheme, parameter_vector)
E

Acquisition scheme summary

total number of measurements: 9
number of b0 measurements: 0
number of DWI shells: 9

shell_index |# of DWIs |bvalue [s/mm^2] |gradient strength [mT/m] |delta [ms] |Delta[ms] |TE[ms]
0           |1         |145             |55                       |10.0       |10.0      |N/A  
1           |1         |259             |73                       |10.0       |10.0      |N/A  
2           |1         |603             |112                      |10.0       |10.0      |N/A  
3           |1         |1175            |156                      |10.0       |10.0      |N/A  
4           |1         |2321            |220                      |10.0       |10.0      |N/A  
5           |1         |5756            |347                      |10.0       |10.0      |N/A  
6           |1         |11482           |490                      |10.0       |10.0      |N/A  
7           |1         |22935           |693                      |10.0       |10.0      |N/A  
8           |1       

array([9.63330982e-01, 9.35363035e-01, 8.56237468e-01, 7.38954339e-01,
       5.50382167e-01, 2.27407407e-01, 5.21240746e-02, 2.73845660e-03,
       1.43871035e-04])